server:
  port: 8080

spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1
      pool-name: master
      maximum-pool-size: 30
      minimum-idle: 5
      jdbc-url: jdbc:mariadb://43.202.203.180:3306/skw
      username: skw
      password: 1234
      driver-class-name: org.mariadb.jdbc.Driver
      connection-timeout: 5000
      idle-timeout: 10000

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    open-in-view: false

logging:
  level:
    org:
      hibernate: info